// County Population Data
let
    Source = Csv.Document(Web.Contents("https://www2.census.gov/programs-surveys/popest/datasets/2010-2019/counties/totals/co-est2019-alldata.csv"),[Delimiter=",", Columns=164, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"SUMLEV", Int64.Type}, {"REGION", Int64.Type}, {"DIVISION", Int64.Type}, {"STATE", Int64.Type}, {"COUNTY", Int64.Type}, {"STNAME", type text}, {"CTYNAME", type text}, {"CENSUS2010POP", Int64.Type}, {"ESTIMATESBASE2010", Int64.Type}, {"POPESTIMATE2010", Int64.Type}, {"POPESTIMATE2011", Int64.Type}, {"POPESTIMATE2012", Int64.Type}, {"POPESTIMATE2013", Int64.Type}, {"POPESTIMATE2014", Int64.Type}, {"POPESTIMATE2015", Int64.Type}, {"POPESTIMATE2016", Int64.Type}, {"POPESTIMATE2017", Int64.Type}, {"POPESTIMATE2018", Int64.Type}, {"POPESTIMATE2019", Int64.Type}, {"NPOPCHG_2010", Int64.Type}, {"NPOPCHG_2011", Int64.Type}, {"NPOPCHG_2012", Int64.Type}, {"NPOPCHG_2013", Int64.Type}, {"NPOPCHG_2014", Int64.Type}, {"NPOPCHG_2015", Int64.Type}, {"NPOPCHG_2016", Int64.Type}, {"NPOPCHG_2017", Int64.Type}, {"NPOPCHG_2018", Int64.Type}, {"NPOPCHG_2019", Int64.Type}, {"BIRTHS2010", Int64.Type}, {"BIRTHS2011", Int64.Type}, {"BIRTHS2012", Int64.Type}, {"BIRTHS2013", Int64.Type}, {"BIRTHS2014", Int64.Type}, {"BIRTHS2015", Int64.Type}, {"BIRTHS2016", Int64.Type}, {"BIRTHS2017", Int64.Type}, {"BIRTHS2018", Int64.Type}, {"BIRTHS2019", Int64.Type}, {"DEATHS2010", Int64.Type}, {"DEATHS2011", Int64.Type}, {"DEATHS2012", Int64.Type}, {"DEATHS2013", Int64.Type}, {"DEATHS2014", Int64.Type}, {"DEATHS2015", Int64.Type}, {"DEATHS2016", Int64.Type}, {"DEATHS2017", Int64.Type}, {"DEATHS2018", Int64.Type}, {"DEATHS2019", Int64.Type}, {"NATURALINC2010", Int64.Type}, {"NATURALINC2011", Int64.Type}, {"NATURALINC2012", Int64.Type}, {"NATURALINC2013", Int64.Type}, {"NATURALINC2014", Int64.Type}, {"NATURALINC2015", Int64.Type}, {"NATURALINC2016", Int64.Type}, {"NATURALINC2017", Int64.Type}, {"NATURALINC2018", Int64.Type}, {"NATURALINC2019", Int64.Type}, {"INTERNATIONALMIG2010", Int64.Type}, {"INTERNATIONALMIG2011", Int64.Type}, {"INTERNATIONALMIG2012", Int64.Type}, {"INTERNATIONALMIG2013", Int64.Type}, {"INTERNATIONALMIG2014", Int64.Type}, {"INTERNATIONALMIG2015", Int64.Type}, {"INTERNATIONALMIG2016", Int64.Type}, {"INTERNATIONALMIG2017", Int64.Type}, {"INTERNATIONALMIG2018", Int64.Type}, {"INTERNATIONALMIG2019", Int64.Type}, {"DOMESTICMIG2010", Int64.Type}, {"DOMESTICMIG2011", Int64.Type}, {"DOMESTICMIG2012", Int64.Type}, {"DOMESTICMIG2013", Int64.Type}, {"DOMESTICMIG2014", Int64.Type}, {"DOMESTICMIG2015", Int64.Type}, {"DOMESTICMIG2016", Int64.Type}, {"DOMESTICMIG2017", Int64.Type}, {"DOMESTICMIG2018", Int64.Type}, {"DOMESTICMIG2019", Int64.Type}, {"NETMIG2010", Int64.Type}, {"NETMIG2011", Int64.Type}, {"NETMIG2012", Int64.Type}, {"NETMIG2013", Int64.Type}, {"NETMIG2014", Int64.Type}, {"NETMIG2015", Int64.Type}, {"NETMIG2016", Int64.Type}, {"NETMIG2017", Int64.Type}, {"NETMIG2018", Int64.Type}, {"NETMIG2019", Int64.Type}, {"RESIDUAL2010", Int64.Type}, {"RESIDUAL2011", Int64.Type}, {"RESIDUAL2012", Int64.Type}, {"RESIDUAL2013", Int64.Type}, {"RESIDUAL2014", Int64.Type}, {"RESIDUAL2015", Int64.Type}, {"RESIDUAL2016", Int64.Type}, {"RESIDUAL2017", Int64.Type}, {"RESIDUAL2018", Int64.Type}, {"RESIDUAL2019", Int64.Type}, {"GQESTIMATESBASE2010", Int64.Type}, {"GQESTIMATES2010", Int64.Type}, {"GQESTIMATES2011", Int64.Type}, {"GQESTIMATES2012", Int64.Type}, {"GQESTIMATES2013", Int64.Type}, {"GQESTIMATES2014", Int64.Type}, {"GQESTIMATES2015", Int64.Type}, {"GQESTIMATES2016", Int64.Type}, {"GQESTIMATES2017", Int64.Type}, {"GQESTIMATES2018", Int64.Type}, {"GQESTIMATES2019", Int64.Type}, {"RBIRTH2011", type number}, {"RBIRTH2012", type number}, {"RBIRTH2013", type number}, {"RBIRTH2014", type number}, {"RBIRTH2015", type number}, {"RBIRTH2016", type number}, {"RBIRTH2017", type number}, {"RBIRTH2018", type number}, {"RBIRTH2019", type number}, {"RDEATH2011", type number}, {"RDEATH2012", type number}, {"RDEATH2013", type number}, {"RDEATH2014", type number}, {"RDEATH2015", type number}, {"RDEATH2016", type number}, {"RDEATH2017", type number}, {"RDEATH2018", type number}, {"RDEATH2019", type number}, {"RNATURALINC2011", type number}, {"RNATURALINC2012", type number}, {"RNATURALINC2013", type number}, {"RNATURALINC2014", type number}, {"RNATURALINC2015", type number}, {"RNATURALINC2016", type number}, {"RNATURALINC2017", type number}, {"RNATURALINC2018", type number}, {"RNATURALINC2019", type number}, {"RINTERNATIONALMIG2011", type number}, {"RINTERNATIONALMIG2012", type number}, {"RINTERNATIONALMIG2013", type number}, {"RINTERNATIONALMIG2014", type number}, {"RINTERNATIONALMIG2015", type number}, {"RINTERNATIONALMIG2016", type number}, {"RINTERNATIONALMIG2017", type number}, {"RINTERNATIONALMIG2018", type number}, {"RINTERNATIONALMIG2019", type number}, {"RDOMESTICMIG2011", type number}, {"RDOMESTICMIG2012", type number}, {"RDOMESTICMIG2013", type number}, {"RDOMESTICMIG2014", type number}, {"RDOMESTICMIG2015", type number}, {"RDOMESTICMIG2016", type number}, {"RDOMESTICMIG2017", type number}, {"RDOMESTICMIG2018", type number}, {"RDOMESTICMIG2019", type number}, {"RNETMIG2011", type number}, {"RNETMIG2012", type number}, {"RNETMIG2013", type number}, {"RNETMIG2014", type number}, {"RNETMIG2015", type number}, {"RNETMIG2016", type number}, {"RNETMIG2017", type number}, {"RNETMIG2018", type number}, {"RNETMIG2019", type number}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"REGION", "DIVISION", "STATE", "COUNTY", "CENSUS2010POP", "ESTIMATESBASE2010", "POPESTIMATE2010", "POPESTIMATE2011", "POPESTIMATE2012", "POPESTIMATE2013", "POPESTIMATE2014", "POPESTIMATE2015", "POPESTIMATE2016", "POPESTIMATE2017", "POPESTIMATE2018"}),
    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns",{"POPESTIMATE2019", "CTYNAME", "STNAME", "SUMLEV"}),
    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each true),
    #"Split Column by Delimiter" = Table.SplitColumn(#"Filtered Rows", "CTYNAME", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, true), {"CTYNAME.1", "CTYNAME.2"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"CTYNAME.1", type text}, {"CTYNAME.2", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"CTYNAME.2"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"STNAME", "State"}, {"SUMLEV", "Summary Level"}, {"CTYNAME.1", "County"}, {"POPESTIMATE2019", "2019 Est Population"}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "State", "State - Copy"),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "County", "County - Copy"),
    #"Merged Columns" = Table.CombineColumns(#"Duplicated Column1",{"State - Copy", "County - Copy"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"StateCounty")
in
    #"Merged Columns"
